### ISSUE TITLE
Build spreadsheet

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/pioneers#2]
Populate the spreadsheet using existing lists of pioneers from underrepresented groups. Be sure to provide attribution for where this data was sourced!

WHEN COMPLETE: hand off the populated spreadsheet with a respectable number of pioneers from each group.

SIGNOFF: I'll likely ask you to flesh out one or more of the groups, but when we reach a good distribution I'll give you the thumbs up. You do NOT need to wait for me to start coming up with a design, so this and #3 can happen in parallel.

**Comment by rrajesh1** [comment]
https://docs.google.com/spreadsheets/d/1FHJrFlqTqCQwhYWhsI_OuNwb2tQaPmv0EneWHvj1jWw/edit?usp=sharing

Here is an update on the spreadsheet, with most of the groups populated at this point. Please let me know if any revision is necessary and what groups should be more fleshed out. Thank you!

**Comment by schanzer** [comment]
@rrajesh1 it looks like a great start! We definitely want to flesh this out with a lot more computing pioneers - I would hope that we'd have at least half a dozen _each_ of pioneers from the demographic columns you've defined. 

And I assume that you're also building a folder of images for these people somewhere as well, no? Unless you're going to go back to find the images when you move on to #3 ?

**Comment by rrajesh1** [comment]
Got it! I was planning to go back for the images after moving on to #3, but I can start building the folder now. Thank you for the feedback!

**Comment by rrajesh1** [comment]
https://docs.google.com/spreadsheets/d/1FHJrFlqTqCQwhYWhsI_OuNwb2tQaPmv0EneWHvj1jWw/edit?usp=sharing

Here is an update on the spreadsheet. Data that were unavailable are highlighted in yellow at the moment (these were mostly in the birth date category). I extended the number of pioneers for all the categories, but the categories for Disabled and Native American/Indigenous pioneers have less than the goal amount now because I was unable to find more pioneers. Please let me know if anything needs to be changed, thank you!

**Comment by shriram** [comment]
This is fantastic, thanks!!!
